project:
  type: manuscript

execute:
  freeze: auto

format:
  html:
    toc: true
  # docx: default
  # jats: default
  pdf: 
    include-in-header: 
      - "tools/preamble.tex"
    template-partials: 
      - "tools/title.tex"
    fontsize: 10pt
    linestretch: 1.25
    link-citations: true
    link-bibliography: true
    bibliography: "tools/references.bib" 
    hypperrefoptions:
    - colorlinks=true,
    - breaklinks=true,
    - citecolor=blue,
    - linkcolor=blue,
    - filecolor=blue,
    - urlcolor=blue

bibliography: "tools/references.bib" 
csl: "tools/apa.csl"